spring.application.name=tcc

influx.url=http://68.221.161.122:8086

influx.bucket=fineco

influx.org=finecompany

influx.token=eyO8AS4bmyyFAtQJYUQIpyRnuSeCN9tJwekGGtTpYqmFlzDak2DwUo7Aq0FNkyy06yxoZ8nDDGVgQPLUL9POiA==