spring.application.name=tcc

# --- Configurações Corrigidas (Padrão V2) ---

# O código procura por 'url', não 'host'
influx.url=https://us-east-1-1.aws.cloud2.influxdata.com

# O código procura por 'bucket', não 'database'
influx.bucket=monitoramento

# IMPORTANTE: A biblioteca V2 exige a organização (geralmente seu e-mail)
influx.org=garcia4.matheus@gmail.com

# Seu token
influx.token=qqER3Oj_0jhTUAMMysSDmngkDiJoGbv8ny9VrC1LFZQx72lcnJEAerMtBARYZhei4GJuG0WTXqtjl6Nj7fAHnw==