spring.application.name=tcc

influx.url=http://13.86.107.141:8086

influx.bucket=finecompany_dev

influx.org=finecompany

influx.token=LCckz0VmCULCKK1xyXJewLJi4VVHUX_SV7Ymtr4e1__3DObZGhPq_Y7w6ikUZhzt3q6p7uyl2Df-fYkXkBjY3A==

# Configurações do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/tcc_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=tcc_user
spring.datasource.password=tcc_password
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true