name: Deploy Automático na VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Conectar na VM e atualizar o Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/tcc/TCC-EngComputacao
          
          git pull origin main
          
          echo "INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }}" > .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
          
          # Baixa o docker-compose V2 atualizado para corrigir o erro ContainerConfig
          sudo curl -sSL "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
          # Remove os containers antigos que ficaram travados
          sudo /usr/local/bin/docker-compose down --remove-orphans
          
          sudo /usr/local/bin/docker-compose up -d --build